# 禁用 trigger，避免每次触发
trigger: none

# 北京时间每周一 00:00 触发
schedules:
  - cron: 0 16 * * 0
    displayName: Weekly Midnight Update
    branches:
      include:
        - main
    always: true

pool:
  name: POOL_NAME_HERE

steps:
  - checkout: self
    fetchDepth: 1
    displayName: Checkout
    persistCredentials: true
  - script: git config user.email "iscnu@scnu.edu.cn" && git config user.name "Azure DevOps Pipeline"
    workingDirectory: $(System.DefaultWorkingDirectory)
  - task: NodeTool@0
    inputs:
      versionSpec: 18.x
    displayName: Install Node.js
  - script: npm install --location=global --force corepack concurrently taze
    displayName: Install Corepack & Concurrently & Taze
  - script: corepack enable
    displayName: Install PNPM
  - script: taze -w
    displayName: Update Dependencies
  - script: pnpm install --no-frozen-lockfile
    displayName: Install Dependencies
  - script: conc "pnpm:lint" "pnpm:check:types" "pnpm:test"
    displayName: Lint & Check Types & Test
  - script: |
      git checkout -b main
      git add -A
      git commit -m "chore: update deps"
      git push --set-upstream origin main
    displayName: Git Add & Commit & Push
    workingDirectory: $(System.DefaultWorkingDirectory)
