/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    VSpacer: typeof import('./src/components/v-spacer/v-spacer.vue')['default']
  }
}
