// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TuiButton: typeof import('thorui-uni/lib/thorui/tui-button/tui-button.vue')['default']
    VSpacer: typeof import('./src/components/VSpacer.vue')['default']
  }
}
