# 检查代码质量、类型和测试
# 提交到主分支或 PR 到主分支时触发
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: POOL_NAME_HERE

steps:
  - checkout: self
    fetchDepth: 1
    displayName: Checkout
    clean: true
  - task: NodeTool@0
    inputs:
      versionSpec: 18.x
    displayName: Install Node.js
  - script: npm install --location=global --force corepack concurrently
    displayName: Install Corepack & Concurrently
  - script: corepack enable
    displayName: Install NPM
  - script: npm install
    displayName: Install Dependencies
  - script: conc "npm:lint" "npm:check:types" "npm:test"
    displayName: Lint & Check Types & Test
