// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VIcon: typeof import('@iconify/vue')['Icon'];
    VRouterView: typeof import('./src/components/VRouterView.vue')['default'];
    VSpacer: typeof import('./src/components/VSpacer.vue')['default'];
  }
}

export {};
