/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonNetworkPublic: typeof import('~icons/carbon/network-public')['default']
    ICarbonVersion: typeof import('~icons/carbon/version')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VPagination: typeof import('./src/components/v-pagination/v-pagination.vue')['default']
    VSpacer: typeof import('./src/components/v-spacer/v-spacer.vue')['default']
  }
}
