/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = { slug: 'slug', index: 'index', signIn: 'sign-in' };

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  };
});
