name: sync

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: git@github.com:MillCloud/presets.git
          destination-repo: git@gitee.com:MillCloud/presets.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
